### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN for Data Explorer app when accessed via link in Footer

### ISSUE THREAD

**Issue by radarsymphony** [cioos-siooc/cioos-siooc-wordpress#14]
Hi there, 

I noticed an issue when attempting to access the DATA EXPLORER app from the link in the Footer on your main CIOOS website. 

## Summary

SSL certificate for `explore.cioos.ca` does not cover/include `explorer.cioos.ca` (with 'r' in domain name). This results in some browsers showing a security page and preventing the user from proceeding to the https://explore.cioos.ca tool when accessing that tool through certain links on main webpage that use "explorer" instead of "explore" in url/domain. 

Basically, there seems to be a mis-match between what the tool is called ("Explorer") and the domain used to access it ("`explore.cioos.ca`"). The domain `explorer.cioos.ca` isn't redirecting properly because the SSL cert that is served doesn't cover the domain that includes the 'r'. 

## Steps to Replicate

Replicated with:
- `Chromium 119.0.6045.123` - stock, no extensions
- `Mozilla Firefox 119.0.1` - increased security thresholds, extensions, etc

1. Open browser (using either Firefox and Chromium produced the issue)
2. Go to https://cioos.ca/
3. Scroll to the bottom of the page
4. In Footer, click on [DATA EXPLORER](https://explorer.cioos.ca/) (or go to https://explorer.cioos.ca)
5. Browser returns a certificate error (`NET::ERR_CERT_COMMON_NAME_INVALID` in chromium, `SSL_ERROR_BAD_CERT_DOMAIN` in Firefox)
6. Inspect SSL certificate and see that only `explore.cioos.ca` is covered by the certificate supplied - `explorer.cioos.ca` is not covered by the certificate. 

**NOTE**: Accessing https://explore.cioos.ca directly works as expected without any SSL errors. Issues seems to be with the `explorer` subdomain not serving a valid SSL that covers that domain. 

## Possible Solutions
I'm providing these as additional way of describing/articulating what I think the problem is. They may not be the actual solution; they are just a way to share what I think is going on. 

- Temporary solution: Update links throughout website to point to explore.cioos.ca, not explorer.cioos.ca
- Add explorer.cioos.ca as an alternative domain to the Let's Encrypt cert's **Subject Alt Names** (SAN) section. If you're using certbot, this might be something like what's shown here: https://eff-certbot.readthedocs.io/en/latest/using.html#changing-a-certificate-s-domains
- Change tool's domain to be explorer.cioos.ca (?)

Please let me know if I can help test or if I can provide additional information :)

## Screenshots 

![image](https://github.com/cioos-siooc/cioos-siooc-wordpress/assets/73671474/6b83e22f-dc8b-4818-a973-baeb43d033ca)

![image](https://github.com/cioos-siooc/cioos-siooc-wordpress/assets/73671474/b54583ab-ded0-4b96-bf3d-fcd4124d38f8)

**Comment by ossenna** [comment]
Hi - I will implement your recommanded temporary solution ie. update links throughout website to point to explore.cioos.ca, not explorer.cioos.ca

**Comment by radarsymphony** [comment]
Hi @ossenna, Thanks for your reply. I'm happy that one of the solutions worked for you. I can confirm that the issue is resolved from my end.
